# Generated by Django 4.2 on 2024-05-21 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asahiyaki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nakagawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='asahiyakievaluation',
            name='image_path',
        ),
        migrations.CreateModel(
            name='NakagawaEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nakagawa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='render.nakagawa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='render.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asahiyakievaluation',
            name='asahiyaki',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='render.asahiyaki'),
            preserve_default=False,
        ),
    ]
