# Generated by Django 4.2 on 2024-06-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0002_asahiyaki_nakagawa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asahiyakievaluation',
            name='is_learned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nakagawaevaluation',
            name='is_learned',
            field=models.BooleanField(default=False),
        ),
    ]
