# Generated by Django 4.2 on 2024-07-05 00:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0005_asahiyaki_is_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='render.user')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('before', 'Before Learning'), ('after', 'After Learning')], max_length=100)),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('qwk', models.FloatField()),
                ('confusion_matrix_image_url', models.URLField()),
                ('classification_report', models.JSONField()),
                ('asahiyaki_evaluations', models.ManyToManyField(related_name='evaluation_results', to='render.asahiyakievaluation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asahiyaki_evaluations', to='render.evaluationsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='render.user')),
            ],
        ),
    ]
