# Generated by Django 4.2 on 2024-07-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0006_evaluationsession_evaluationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='nakagawaevaluation',
            name='is_example',
            field=models.BooleanField(default=False),
        ),
    ]
