# Generated by Django 4.2 on 2024-07-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0007_nakagawaevaluation_is_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nakagawaevaluation',
            name='is_example',
        ),
        migrations.AddField(
            model_name='nakagawa',
            name='is_example',
            field=models.BooleanField(default=False),
        ),
    ]
