# Generated by Django 4.2 on 2024-07-24 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0009_nakagawa_correct_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='asahiyakievaluation',
            name='sessuion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='render.evaluationsession'),
        ),
        migrations.AddField(
            model_name='nakagawaevaluation',
            name='sessuion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='render.evaluationsession'),
        ),
    ]
