# Generated by Django 4.2 on 2024-07-24 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0010_asahiyakievaluation_sessuion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nakagawaevaluation',
            old_name='sessuion',
            new_name='session',
        ),
        migrations.RemoveField(
            model_name='asahiyakievaluation',
            name='sessuion',
        ),
        migrations.AddField(
            model_name='asahiyakievaluation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='render.evaluationsession'),
        ),
    ]
